# Generated by Django 3.1.7 on 2021-03-27 02:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_date', models.DateField()),
                ('course_fee', models.CharField(max_length=50)),
                ('batch_status', models.CharField(choices=[('3', 'completed'), ('2', 'Ongoing'), ('1', 'Yet to beign')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.date(2021, 3, 27))),
                ('enquiryid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiryid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enquirydate', models.DateField(default=datetime.date(2021, 3, 27))),
                ('followup_date', models.DateField()),
                ('status', models.CharField(choices=[('2', 'Admitted'), ('3', 'Cancel'), ('1', 'call_back')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courses')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courses'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('enquiryid', models.CharField(max_length=50)),
                ('coursefee', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2021, 3, 27))),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.batch')),
            ],
        ),
    ]
