# Generated by Django 3.1.7 on 2021-03-31 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('2', 'Ongoing'), ('3', 'completed'), ('1', 'Yet to beign')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
    ]
