# Generated by Django 3.1.7 on 2021-04-13 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210405_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='councillor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='councillor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 13)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Yet to beign', 'Yet to beign'), ('completed', 'completed')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 4, 13)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('call_back', 'call_back'), ('Cancel', 'Cancel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 4, 13)),
        ),
    ]
