# Generated by Django 3.1.7 on 2021-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210413_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='councillor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('completed', 'completed'), ('Ongoing', 'Ongoing'), ('Yet to beign', 'Yet to beign')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Cancel', 'Cancel'), ('call_back', 'call_back')], max_length=20),
        ),
    ]
